package com.grapheneterminal.modules

import android.content.Context
import android.os.BatteryManager
import android.os.PowerManager
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.grapheneterminal.modules.NativeGrapheneCoreSpec // Generated by Codegen

class GrapheneCoreModule(reactContext: ReactApplicationContext) : NativeGrapheneCoreSpec(reactContext) {

    override fun getName() = "GrapheneCore"

    override fun getBatteryLevel(promise: Promise) {
        try {
            val batteryManager = reactApplicationContext.getSystemService(Context.BATTERY_SERVICE) as BatteryManager
            // Android returns int 0-100, we convert to float 0.0-1.0
            val level = batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY) / 100.0
            promise.resolve(level)
        } catch (e: Exception) {
            promise.reject("BATTERY_ERROR", e)
        }
    }

    override fun getThermalState(promise: Promise) {
        // Simple mock since Thermal API requires newer Android versions (API 29+)
        // In a real app, uses PowerManager.getCurrentThermalStatus()
        promise.resolve("NOMINAL") 
    }
}