#import "GrapheneCore.h"
// 1. The Generated Spec (The C++ Contract !!!)
#import "NativeGrapheneCoreSpec.h"
// 2. The Swift Header (The Logic)
// This file is auto-generated by Xcode from your Swift code
#import "GrapheneTerminal-Swift.h"

@implementation GrapheneCore

RCT_EXPORT_MODULE()

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeGrapheneCoreSpecJSI>(params);
}

- (void)getBatteryLevel:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  GrapheneCoreImpl *impl = [[GrapheneCoreImpl alloc] init];
  float level = [impl getBatteryLevel];
  if (level < 0) level = 1.0; 
  resolve(@(level));
}

- (void)getThermalState:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  GrapheneCoreImpl *impl = [[GrapheneCoreImpl alloc] init];
  NSString *state = [impl getThermalState];
  resolve(state);
}

@end
